---
title: "Progress log"
---

Use this page to track your progress and keep a log of your contributions to the project, please update this each time you work on your project, it is generally a good habit to adopt.

If you are working as a team, at the end, you can duplicate the project and add it to your individual portfolio websites. If you do, you **MUST** retain attribution to your teammates. Removing attribution would constitute plagiarism.

## To-do

* [ ] Explore possible topics by brainstorming with GPT 
* [ ] write a technical methods sections for K-means
* [ ] write a technical methods sections for PCA

... etc 

## Member-1:

[Gentry Lamb](../index.qmd#about-us)

**Weekly project contribution log:**


**11-21-2024** 

* [x] Coordinate with team member to set up first project meeting


**11-25-2024** 

* [x] Begin working on data collection and researching use of Selenium 


**12-01-2024** 

* [x] Write data collection code


**12-06-2024**

* [x] Write literature review and put together the landing page 


**12-07-2024**

* [x] Update data collection code to include distances
* [x] Write data cleaning code
* [x] Start writing EDA code


**12-08-2024**

* [x] Complete writing EDA code and start on Unsupervised Learning Code


**12-09-2024**

* [x] Complete writing Unsupervised Learning Code and start on write-up


**12-10-2024**

* [x] Complete write-up for Unsupervised Learning
* [x] Restructure/Format all technical details page
* [x] Complete all code and write-ups, begin working on non-technical report


**12-11-2024**



## Member-2:

[Chase Clemence](../index.qmd#about-us)

**Weekly project contribution log:**


**11-21-2024** 

* [x] Attend first group meeting


**12-06-2024**

* [x] Complete literature review and put together the landing page 


**12-07-2024**

* [x] Wrote technical details for data collection
* [x] Refined the landing page to include more information
* [x] Wrote technical details for data cleaning


**12-08-2024**

* [x] Wrote technical details for EDA
* [x] Coded up a lot of the supervised learning portion


**12-08-2024**

* [x] Finished the code for supervised learning


**12-10-2024**

* [x] Completed the technical details for supervised learning